- name: install epel
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
- name: install ngnix
  action: "{{ ansible_pkg_mgr }} name=ngnix state=present"
- name: upload default index.html
  get_url: url=https://www.nginx.com dest=/usr/share/nginx/html/ mode=0644 validate_certs=no
  notify: 
    - restart ngnix web server