- name: install nginx
  action: "{{ ansible_pkg_mgr }} name=ngnix state=present update_cache=yes"
- name: upload default index.html
  get_rul: url=https://www.nginx.com dest=/usr/share/nginx/html/ mode=0644 validate_certs=no
  notify:
    - restart ngnix