- name: install epel
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
- name: install ngix web server
  action: "{{ ansible_pkg_mfr }} name=nginx state present"
- name: upload default index.html
  get_url: url=https://www.nginx.com dest=/usr/share/nginx/html/ mode=0644
  notify:
    - restart nginx web server
- name: start nginx
  services: name=ngix state=started