- name: nfs client dir
  file:
    path: "{{ ansible_user_dir }}/nfs"
    state: directory

- name: mount dir as client
  become: yes
  mount:
    name: "{{ ansible_user_dir }}/nfs"
    src: "{{ ansible_env.SSH_CLIENT.split()[0] }}: /home/vagrant/nfs_shared"
    fstype: nfs
    opts: nfsvers=3
    state: mounted 