---
- name: ssh_config
  hosts: nodes
  gatehr_facts: no

  tasks:
    - name: ssh-keygen
      connection: local
      command: "ssh-kegen -b 2048 -t rsa -f ~/.ssh/test -q -N ''"
      ignore_errors: yes
      run_once: true

    - name: read pub
      connection: local
      command: "cat ~/.ssh/test.pub"
      register: id_pub
      run_once: true

    - name: remote authorized_keys
      lineinfile:
        dest: /home/vagrant/.ssh/authorized_keys
        line: "{{ test.stdout }}"

---
- name: known_host
  hosts: nodes
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
    register: keyscan
  
  - lineinfile: 
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"